### ISSUE TITLE
Feedback for v0.03

### ISSUE THREAD

**Issue by nirandiw** [CS2103JAN2017-T11-B1/main#120]
# User Guide.

- Good job adding a lot of screen shots. In future, you might want to use partial screenshots capturing only the part in concern. Otherwise, you'll have to update all screenshots when some minor detail of the GUI changes.

- The 'Command summary' section will be used heavily by our testers. Try to make it easy to use as possible. e.g. give examples for each command.

- Ctrl+Z and Ctrl+Y are not input commands. There has to be a input command to undo and redo. 
# Developer Guide

- Figure 2.1.1 : Architecture Diagram: are you still using a web component?

- Some NFRs are vague. 

- Good product sruvey

- Explain how your design support undo/redo. There are multiple ways this can be done, so it will be useful to explain how you do it and why you chose to do it that way.
 
- Similarly, you can explain other interesting design decisions you made.

**Comment by alvinlyj** [comment]
To be completed in V0.5
