### ISSUE TITLE
User will be able to search a task by keyword

### ISSUE THREAD

**Issue by joelleejh** [CS2103JAN2017-T11-B1/main#25]
Locate details of task without having to go through the entire list

**Comment by alvinlyj** [comment]
User able to search tasks by name (closing Issue #39) and date (closing issue #49) achieved in PR #61. 

Supporting of searching by categories will be achieved in V0.4 when categories are implemented. Hence target accomplished milestone to be V0.4

**Comment by alvinlyj** [comment]
Issue #50 resolved
