### ISSUE TITLE
User will be able to view events in a sorted manner

### ISSUE THREAD

**Issue by KohJunWei** [CS2103JAN2017-T11-B1/main#31]
So that they can list all tasks by certain filters

**Comment by alvinlyj** [comment]
Functionality to be changed to correctly place new events and updated events in the correct order for smoother user experience

**Comment by alvinlyj** [comment]
Previously tagged issues are closed in a bid to streamline user experience.

**Comment by alvinlyj** [comment]
Completed in PR #129
